apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
data:
  application.yaml: |+
    server:
      port: {{ .Values.image.containerPort }}

    wfd:
      menu:
        appetizers:
          url: http://{{ .Release.Name }}-{{ .Values.appetizer.url.core }}
        entrees:
          url: http://{{ .Release.Name }}-{{ .Values.entree.url.core }}
        desserts:
          url: http://{{ .Release.Name }}-{{ .Values.dessert.url.core }}
