spring:
  application:
    name: menu-service
#  cloud:
#    client:
#      hostname: localhost

server:
  port: 8180

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true

wfd:
  menu:
    appetizers:
      url: http://appetizer-service/appetizers
    entrees:
      url: http://entree-service/entrees
    desserts:
      url: http://dessert-service/desserts
      
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
